import { defineConfig } from "oxlint";

import config from "./index.js";

export default defineConfig({
  extends: [config],
  // Vendored third-party bundle, generated by esbuild; not held to this config.
  ignorePatterns: ["anti-slop/index.js"],
  overrides: [
    {
      files: ["index.js", "src/index.ts"],
      rules: {
        // The rule inventory is documentation-dense by design; its long
        // section comments are the point of the file.
        "awesomeness/no-novel-comments": "off",
        "max-lines": "off",
      },
    },
    {
      // The CLI source lives in src/ so the build can emit it, but it is CLI
      // code: the shipped `**/bin/**` override does not reach it here.
      files: ["src/init.ts"],
      rules: {
        "anti-slop/no-unknown-parameters": "off",
        "node/no-sync": "off",
      },
    },
  ],
});
